namespace SchemeReady.Api.Models;

/// <summary>
/// Append-only audit record. The key is <c>bigint GENERATED BY DEFAULT AS IDENTITY</c>,
/// replacing the <c>INT IDENTITY(1,1)</c> of the deleted MS SQL <c>schema.sql</c> (R1.7).
///
/// Phase A declares the persistence shape and Phase A's writers use it for the two audit
/// events this phase owes: the illustrative-flag change of R2.7 and the persistence
/// failure of R1.16/R1.17. The append-only GRANT/REVOKE, rate limits and the full closed
/// action set arrive in Phase G.
/// </summary>
public class AuditEvent
{
    public long Id { get; set; }

    public DateTime OccurredAt { get; set; } = DateTime.UtcNow;

    /// <summary>Authenticated user identifier, or <c>"anonymous"</c>.</summary>
    public string ActorId { get; set; } = "anonymous";

    /// <summary>
    /// Drawn from the closed set: <c>AuthAttempt</c>, <c>AuthorizationDenied</c>,
    /// <c>DocumentUpload</c>, <c>DocumentRetrieval</c>, <c>DocumentDeletion</c>,
    /// <c>SchemeChange</c>, <c>PartnerChange</c>, <c>ScoringWeightChange</c>,
    /// <c>IllustrativeFlagChange</c>, <c>ApplicationHandoff</c>,
    /// <c>PersistenceFailure</c>, <c>SuspectedTokenReplay</c>.
    /// </summary>
    public string ActionType { get; set; } = string.Empty;

    public string EntityType { get; set; } = string.Empty;

    /// <summary>Empty string when the action has no target entity.</summary>
    public string EntityId { get; set; } = string.Empty;

    public string SourceIpAddress { get; set; } = string.Empty;

    /// <summary>Exactly <c>Success</c> or <c>Failure</c>.</summary>
    public string Outcome { get; set; } = string.Empty;

    /// <summary>
    /// Serialised jsonb detail. An allow-list keeps passwords, hashes, tokens and document
    /// bytes out of this column (R9.3).
    /// </summary>
    public string? Detail { get; set; }
}
