import React from 'react';
import { 
  Building2, 
  Phone, 
  Mail, 
  ExternalLink, 
  ShieldCheck, 
  HeartHandshake, 
  Globe2,
  Sparkles
} from 'lucide-react';

export default function LandingFooter({ onStartOnboarding, onExploreSchemes, lang = 'en' }) {
  const isHindi = lang === 'hi';

  return (
    <footer className="bg-slate-950 text-slate-400 text-xs border-t border-slate-800">
      
      {/* Upper Call to Action Glowing Banner */}
      <div className="bg-gradient-to-r from-emerald-950 via-slate-900 to-teal-950 border-b border-emerald-500/20 py-12 px-4 sm:px-6">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-6 text-center md:text-left">
          <div className="space-y-2 max-w-2xl">
            <div className="inline-flex items-center space-x-2 bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 px-3 py-1 rounded-full text-[10px] font-mono font-bold uppercase tracking-wider">
              <Sparkles className="w-3.5 h-3.5" />
              <span>{isHindi ? 'राष्ट्रीय रियायती ऋण पहल' : 'National Concessional Credit Initiative'}</span>
            </div>
            <h3 className="text-2xl sm:text-3xl font-black text-white tracking-tight">
              {isHindi ? 'अपनी उद्यमशीलता यात्रा को वित्तपोषित करने के लिए तैयार हैं?' : 'Ready to Fund Your Entrepreneurial Journey?'}
            </h3>
            <p className="text-xs sm:text-sm text-slate-300">
              {isHindi 
                ? '2 मिनट में अपनी पात्रता जांचें, एआई द्वारा अपना बिजनेस प्लान बनाएं, और सक्रिय सरकारी चैनल पार्टनर्स से सीधा मार्गदर्शन प्राप्त करें।' 
                : 'Check your eligibility in 2 minutes, get your business plan generated by AI, and receive direct routing to active government Channel Partners.'}
            </p>
          </div>

          <div className="flex flex-wrap items-center justify-center gap-3">
            <button
              onClick={onStartOnboarding}
              className="bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-black text-xs sm:text-sm px-6 py-3.5 rounded-xl shadow-lg shadow-emerald-500/25 transition-all transform hover:scale-[1.02] active:scale-95 cursor-pointer"
            >
              {isHindi ? 'निःशुल्क स्मार्ट ऑनबोर्डिंग शुरू करें' : 'Start Free Smart Onboarding'}
            </button>
            <button
              onClick={onExploreSchemes}
              className="bg-slate-900 hover:bg-slate-800 text-white font-bold text-xs sm:text-sm px-5 py-3.5 rounded-xl border border-white/20 transition-all cursor-pointer"
            >
              {isHindi ? '6 योजनाएं देखें' : 'Explore 6 Schemes'}
            </button>
          </div>
        </div>
      </div>

      {/* Main Footer Links */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 py-12">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          
          {/* Col 1: Brand & National Emblem */}
          <div className="space-y-4">
            <div className="flex items-center space-x-3">
              <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-emerald-600 to-teal-500 flex items-center justify-center text-white font-black text-base shadow-md">
                SR
              </div>
              <div>
                <h4 className="text-white font-black text-sm tracking-tight">
                  {isHindi ? 'स्कीम रेडी एआई' : 'SchemeReady AI'}
                </h4>
                <p className="text-[10px] text-emerald-400 font-mono">
                  {isHindi ? 'उद्यम सारथी प्लेटफॉर्म' : 'Udyam Saarthi Platform'}
                </p>
              </div>
            </div>
            <p className="text-[11px] leading-relaxed text-slate-400">
              {isHindi 
                ? 'राष्ट्रीय रियायती उद्यमिता एवं ऋण तत्परता मंच, जो अनुसूचित जाति, अन्य पिछड़ा वर्ग और उभरते सूक्ष्म उद्यमियों के लिए ऋण अस्वीकरण को समाप्त करने हेतु डिज़ाइन किया गया है।' 
                : 'National Concessional Entrepreneurship & Credit Readiness Platform designed to eliminate last-mile loan rejections for SC, OBC, and emerging micro-entrepreneurs.'}
            </p>
            <div className="flex items-center space-x-2 text-[10px] text-slate-400 font-mono">
              <ShieldCheck className="w-4 h-4 text-emerald-500" />
              <span>{isHindi ? 'PM-SURAJ एवं NSFDC संरेखित' : 'PM-SURAJ & NSFDC Aligned'}</span>
            </div>
          </div>

          {/* Col 2: Concessional Products */}
          <div className="space-y-3">
            <h5 className="text-white font-bold uppercase tracking-wider text-[11px]">
              {isHindi ? 'वित्तीय योजनाएं' : 'Financial Schemes'}
            </h5>
            <ul className="space-y-2 text-[11px]">
              <li><a href="#schemes" className="hover:text-emerald-400 transition-colors">{isHindi ? 'माइक्रो क्रेडिट योजना (₹1.5 लाख @ 5%)' : 'Micro Credit Scheme (₹1.5L @ 5%)'}</a></li>
              <li><a href="#schemes" className="hover:text-emerald-400 transition-colors">{isHindi ? 'महिला समृद्धि योजना (₹1.4 लाख @ 4%)' : 'Mahila Samriddhi Yojana (₹1.4L @ 4%)'}</a></li>
              <li><a href="#schemes" className="hover:text-emerald-400 transition-colors">{isHindi ? 'मियादी ऋण डबल डेकर (₹50 लाख तक)' : 'Term Loan Double Decker (Up to ₹50L)'}</a></li>
              <li><a href="#schemes" className="hover:text-emerald-400 transition-colors">{isHindi ? 'ग्रीन बिजनेस योजना (सोलर एवं ईवी)' : 'Green Business Scheme (Solar & EV)'}</a></li>
              <li><a href="#schemes" className="hover:text-emerald-400 transition-colors">{isHindi ? 'स्टैंड-अप इंडिया / पीएमईजीपी अभिसरण' : 'Stand-Up India / PMEGP Convergence'}</a></li>
              <li><a href="#schemes" className="hover:text-emerald-400 transition-colors">{isHindi ? 'शैक्षणिक रियायती ऋण' : 'Educational Concessional Loan'}</a></li>
            </ul>
          </div>

          {/* Col 3: Channel Partners & Network */}
          <div className="space-y-3">
            <h5 className="text-white font-bold uppercase tracking-wider text-[11px]">
              {isHindi ? 'चैनल पार्टनर्स' : 'Channel Partners'}
            </h5>
            <ul className="space-y-2 text-[11px]">
              <li><a href="#partners" className="hover:text-emerald-400 transition-colors">{isHindi ? 'कर्नाटक डॉ. बी.आर. अंबेडकर निगम' : 'Karnataka Dr. B.R. Ambedkar Corp'}</a></li>
              <li><a href="#partners" className="hover:text-emerald-400 transition-colors">{isHindi ? 'महात्मा फुले पिछड़ा वर्ग निगम (महाराष्ट्र)' : 'Mahatma Phule BC Corp (Maharashtra)'}</a></li>
              <li><a href="#partners" className="hover:text-emerald-400 transition-colors">{isHindi ? 'यूपी एससी वित्त एवं विकास निगम (UPSCDC)' : 'UP SC Finance & Dev Corp (UPSCDC)'}</a></li>
              <li><a href="#partners" className="hover:text-emerald-400 transition-colors">{isHindi ? 'तमिलनाडु टाहडको (TAHDCO) निगम' : 'Tamil Nadu TAHDCO Corporation'}</a></li>
              <li><a href="#partners" className="hover:text-emerald-400 transition-colors">{isHindi ? 'क्षेत्रीय ग्रामीण बैंक (RRBs)' : 'Regional Rural Banks (RRBs)'}</a></li>
              <li><a href="#partners" className="hover:text-emerald-400 transition-colors">{isHindi ? 'सार्वजनिक क्षेत्र के बैंक नेटवर्क' : 'Public Sector Banks Network'}</a></li>
            </ul>
          </div>

          {/* Col 4: Official Helpline & Portals */}
          <div className="space-y-3">
            <h5 className="text-white font-bold uppercase tracking-wider text-[11px]">
              {isHindi ? 'सरकारी संपर्क' : 'Government Contact'}
            </h5>
            <div className="space-y-2 text-[11px]">
              <div className="flex items-center space-x-2">
                <Phone className="w-3.5 h-3.5 text-emerald-400" />
                <span>{isHindi ? 'टोल-फ्री: 1800-11-2026' : 'Toll-Free: 1800-11-2026'}</span>
              </div>
              <div className="flex items-center space-x-2">
                <Mail className="w-3.5 h-3.5 text-emerald-400" />
                <span>support@schemeready.gov.in</span>
              </div>
              <div className="pt-2 text-[10px] text-slate-400 space-y-1">
                <p>{isHindi ? 'सामाजिक न्याय और अधिकारिता मंत्रालय' : 'Ministry of Social Justice & Empowerment'}</p>
                <p>{isHindi ? 'शास्त्री भवन, नई दिल्ली - 110001' : 'Shastri Bhawan, New Delhi - 110001'}</p>
              </div>
            </div>
          </div>

        </div>

        {/* Bottom Legal & Tricolor Bar */}
        <div className="pt-8 mt-8 border-t border-slate-900 flex flex-col sm:flex-row items-center justify-between gap-3 text-[11px] text-slate-400">
          <p>
            {isHindi 
              ? '© 2026 स्कीम रेडी (उद्यम सारथी)। राष्ट्रीय नवाचार एवं लाभार्थी सशक्तिकरण हेतु निर्मित।' 
              : '© 2026 SchemeReady (Udyam Saarthi). Built for National Innovation & Beneficiary Empowerment.'}
          </p>
          <div className="flex items-center space-x-4">
            <span className="text-emerald-400">
              {isHindi ? '● 100% संप्रभु डेटा गोपनीयता' : '● 100% Sovereign Data Privacy'}
            </span>
            <span className="text-slate-400">|</span>
            <span>
              {isHindi ? 'डिजिलॉकर एवं PM-SURAJ एकीकृत' : 'DigiLocker & PM-SURAJ Integrated'}
            </span>
          </div>
        </div>
      </div>

    </footer>
  );
}
