// <auto-generated /> — NOT auto-generated. Hand-authored in a sandbox with no .NET SDK.
// Validate on your machine with `dotnet ef migrations has-pending-model-changes`; if it
// reports pending changes, delete this Migrations folder and run
// `dotnet ef migrations add InitialPostgres`. SchemeReadyDbContext is the source of truth.
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchemeReady.Api.Data;

#nullable disable

namespace SchemeReady.Api.Migrations
{
    [DbContext(typeof(SchemeReadyDbContext))]
    [Migration("20260101000000_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
                modelBuilder
                    .HasAnnotation("ProductVersion", "8.0.11")
                    .HasAnnotation("Relational:MaxIdentifierLength", 63);

                NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

                modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                    {
                        b.Property<string>("Id")
                            .HasColumnType("text");

                        b.Property<string>("ConcurrencyStamp")
                            .IsConcurrencyToken()
                            .HasColumnType("text");

                        b.Property<string>("Name")
                            .HasMaxLength(256)
                            .HasColumnType("character varying(256)");

                        b.Property<string>("NormalizedName")
                            .HasMaxLength(256)
                            .HasColumnType("character varying(256)");

                        b.HasKey("Id");

                        b.HasIndex("NormalizedName")
                            .IsUnique()
                            .HasDatabaseName("RoleNameIndex");

                        b.ToTable("AspNetRoles", (string)null);
                    });

                modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                    {
                        b.Property<int>("Id")
                            .ValueGeneratedOnAdd()
                            .HasColumnType("integer");

                        NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                        b.Property<string>("ClaimType")
                            .HasColumnType("text");

                        b.Property<string>("ClaimValue")
                            .HasColumnType("text");

                        b.Property<string>("RoleId")
                            .IsRequired()
                            .HasColumnType("text");

                        b.HasKey("Id");

                        b.HasIndex("RoleId");

                        b.ToTable("AspNetRoleClaims", (string)null);
                    });

                modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                    {
                        b.Property<int>("Id")
                            .ValueGeneratedOnAdd()
                            .HasColumnType("integer");

                        NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                        b.Property<string>("ClaimType")
                            .HasColumnType("text");

                        b.Property<string>("ClaimValue")
                            .HasColumnType("text");

                        b.Property<string>("UserId")
                            .IsRequired()
                            .HasColumnType("text");

                        b.HasKey("Id");

                        b.HasIndex("UserId");

                        b.ToTable("AspNetUserClaims", (string)null);
                    });

                modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                    {
                        b.Property<string>("LoginProvider")
                            .HasColumnType("text");

                        b.Property<string>("ProviderKey")
                            .HasColumnType("text");

                        b.Property<string>("ProviderDisplayName")
                            .HasColumnType("text");

                        b.Property<string>("UserId")
                            .IsRequired()
                            .HasColumnType("text");

                        b.HasKey("LoginProvider", "ProviderKey");

                        b.HasIndex("UserId");

                        b.ToTable("AspNetUserLogins", (string)null);
                    });

                modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                    {
                        b.Property<string>("UserId")
                            .HasColumnType("text");

                        b.Property<string>("RoleId")
                            .HasColumnType("text");

                        b.HasKey("UserId", "RoleId");

                        b.HasIndex("RoleId");

                        b.ToTable("AspNetUserRoles", (string)null);
                    });

                modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                    {
                        b.Property<string>("UserId")
                            .HasColumnType("text");

                        b.Property<string>("LoginProvider")
                            .HasColumnType("text");

                        b.Property<string>("Name")
                            .HasColumnType("text");

                        b.Property<string>("Value")
                            .HasColumnType("text");

                        b.HasKey("UserId", "LoginProvider", "Name");

                        b.ToTable("AspNetUserTokens", (string)null);
                    });

                modelBuilder.Entity("SchemeReady.Api.Auth.ApplicationUser", b =>
                    {
                        b.Property<string>("Id")
                            .HasColumnType("text");

                        b.Property<int>("AccessFailedCount")
                            .HasColumnType("integer");

                        b.Property<string>("ConcurrencyStamp")
                            .IsConcurrencyToken()
                            .HasColumnType("text");

                        b.Property<DateTime>("CreatedAt")
                            .HasColumnType("timestamp with time zone");

                        b.Property<string>("DisplayName")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("Email")
                            .HasMaxLength(256)
                            .HasColumnType("character varying(256)");

                        b.Property<bool>("EmailConfirmed")
                            .HasColumnType("boolean");

                        b.Property<bool>("LockoutEnabled")
                            .HasColumnType("boolean");

                        b.Property<DateTimeOffset?>("LockoutEnd")
                            .HasColumnType("timestamp with time zone");

                        b.Property<string>("NormalizedEmail")
                            .HasMaxLength(256)
                            .HasColumnType("character varying(256)");

                        b.Property<string>("NormalizedUserName")
                            .HasMaxLength(256)
                            .HasColumnType("character varying(256)");

                        b.Property<string>("PasswordHash")
                            .HasColumnType("text");

                        b.Property<string>("PhoneNumber")
                            .HasColumnType("text");

                        b.Property<bool>("PhoneNumberConfirmed")
                            .HasColumnType("boolean");

                        b.Property<string>("SecurityStamp")
                            .HasColumnType("text");

                        b.Property<bool>("TwoFactorEnabled")
                            .HasColumnType("boolean");

                        b.Property<string>("UserName")
                            .HasMaxLength(256)
                            .HasColumnType("character varying(256)");

                        b.HasKey("Id");

                        b.HasIndex("NormalizedEmail")
                            .HasDatabaseName("EmailIndex");

                        b.HasIndex("NormalizedUserName")
                            .IsUnique()
                            .HasDatabaseName("UserNameIndex");

                        b.ToTable("AspNetUsers", (string)null);
                    });

                modelBuilder.Entity("SchemeReady.Api.Auth.OfficerPartnerAssignment", b =>
                    {
                        b.Property<string>("UserId")
                            .HasColumnType("text");

                        b.Property<DateTime>("AssignedAt")
                            .HasColumnType("timestamp with time zone");

                        b.Property<string>("PartnerId")
                            .IsRequired()
                            .HasMaxLength(64)
                            .HasColumnType("text");

                        b.HasKey("UserId");

                        b.HasIndex("PartnerId");

                        b.ToTable("OfficerPartnerAssignments", (string)null);
                    });

                modelBuilder.Entity("SchemeReady.Api.Auth.RefreshToken", b =>
                    {
                        b.Property<Guid>("Id")
                            .HasColumnType("uuid");

                        b.Property<DateTime>("ExpiresAt")
                            .HasColumnType("timestamp with time zone");

                        b.Property<DateTime>("IssuedAt")
                            .HasColumnType("timestamp with time zone");

                        b.Property<string>("ReplacedByHash")
                            .HasColumnType("text");

                        b.Property<DateTime?>("RevokedAt")
                            .HasColumnType("timestamp with time zone");

                        b.Property<string>("TokenHash")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("UserId")
                            .IsRequired()
                            .HasColumnType("text");

                        b.HasKey("Id");

                        b.HasIndex("TokenHash")
                            .IsUnique();

                        b.HasIndex("UserId")
                            .HasDatabaseName("ix_refresh_tokens_user_live")
                            .HasFilter("\"RevokedAt\" IS NULL");

                        b.ToTable("RefreshTokens", (string)null);
                    });

                modelBuilder.Entity("SchemeReady.Api.Data.ApplicationPackRow", b =>
                    {
                        b.Property<string>("ApplicationId")
                            .HasMaxLength(64)
                            .HasColumnType("text");

                        b.Property<string>("ApplicantBusinessType")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("AssignedPartnerId")
                            .HasMaxLength(64)
                            .HasColumnType("text");

                        b.Property<string>("District")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("FullDossierJson")
                            .IsRequired()
                            .HasColumnType("jsonb");

                        b.Property<DateTime>("GeneratedDate")
                            .HasColumnType("timestamp with time zone");

                        b.Property<string>("HandoffReferenceNumber")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("MissingDocuments")
                            .IsRequired()
                            .HasColumnType("jsonb")
                            .HasColumnName("MissingDocumentsJson");

                        b.Property<string>("OwnerUserId")
                            .HasColumnType("text");

                        b.Property<string>("SelectedSchemeId")
                            .IsRequired()
                            .HasMaxLength(64)
                            .HasColumnType("text");

                        b.Property<string>("TrackingStatus")
                            .IsRequired()
                            .HasColumnType("text");

                        b.HasKey("ApplicationId");

                        b.HasIndex("ApplicantBusinessType");

                        b.HasIndex("AssignedPartnerId");

                        b.HasIndex("District");

                        b.HasIndex("GeneratedDate");

                        b.HasIndex("OwnerUserId");

                        b.ToTable("ApplicationPacks", (string)null);
                    });

                modelBuilder.Entity("SchemeReady.Api.Models.AuditEvent", b =>
                    {
                        b.Property<long>("Id")
                            .ValueGeneratedOnAdd()
                            .HasColumnType("bigint");

                        NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                        b.Property<string>("ActionType")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("ActorId")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("Detail")
                            .HasColumnType("jsonb");

                        b.Property<string>("EntityId")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("EntityType")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<DateTime>("OccurredAt")
                            .HasColumnType("timestamp with time zone");

                        b.Property<string>("Outcome")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("SourceIpAddress")
                            .IsRequired()
                            .HasColumnType("text");

                        b.HasKey("Id");

                        b.HasIndex("OccurredAt")
                            .IsDescending();

                        b.ToTable("AuditEvents", (string)null);
                    });

                modelBuilder.Entity("SchemeReady.Api.Models.ChannelPartner", b =>
                    {
                        b.Property<string>("Id")
                            .HasMaxLength(64)
                            .HasColumnType("text");

                        b.Property<string>("Address")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("ApplicationMode")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("ContactNumber")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("ContactPerson")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<double>("DistanceKm")
                            .HasColumnType("double precision");

                        b.Property<string>("District")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("DocumentRequirements")
                            .IsRequired()
                            .HasColumnType("jsonb");

                        b.Property<string>("InstitutionName")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("InstitutionType")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<bool>("IsIllustrative")
                            .ValueGeneratedOnAdd()
                            .HasColumnType("boolean")
                            .HasDefaultValue(true);

                        b.Property<bool>("IsOnlineSubmissionAvailable")
                            .HasColumnType("boolean");

                        b.Property<DateTime>("LastVerifiedDate")
                            .HasColumnType("timestamp with time zone");

                        b.Property<double>("Latitude")
                            .HasColumnType("double precision");

                        b.Property<double>("Longitude")
                            .HasColumnType("double precision");

                        b.Property<string>("Pincode")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("State")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("SupportedSchemes")
                            .IsRequired()
                            .HasColumnType("jsonb");

                        b.Property<string>("VerificationSourceReference")
                            .HasMaxLength(300)
                            .HasColumnType("text");

                        b.Property<DateTime?>("VerifiedOn")
                            .HasColumnType("timestamp with time zone");

                        b.HasKey("Id");

                        b.HasIndex("District");

                        b.ToTable("ChannelPartners", (string)null);
                    });

                modelBuilder.Entity("SchemeReady.Api.Models.Scheme", b =>
                    {
                        b.Property<string>("Id")
                            .HasMaxLength(64)
                            .HasColumnType("text");

                        b.Property<string>("ApplicationMode")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("Description")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("EligibleBusinessTypes")
                            .IsRequired()
                            .HasColumnType("jsonb");

                        b.Property<string>("GenderRestriction")
                            .IsRequired()
                            .ValueGeneratedOnAdd()
                            .HasColumnType("text")
                            .HasDefaultValue("Any");

                        b.Property<decimal>("IncomeLimit")
                            .HasColumnType("numeric(12,2)");

                        b.Property<decimal>("InterestRate")
                            .HasColumnType("numeric(5,2)");

                        b.Property<bool>("IsIllustrative")
                            .ValueGeneratedOnAdd()
                            .HasColumnType("boolean")
                            .HasDefaultValue(true);

                        b.Property<DateTime>("LastVerifiedDate")
                            .HasColumnType("timestamp with time zone");

                        b.Property<int>("MaximumAge")
                            .HasColumnType("integer");

                        b.Property<decimal>("MaximumProjectCost")
                            .HasColumnType("numeric(12,2)");

                        b.Property<int>("MaximumTenureMonths")
                            .HasColumnType("integer");

                        b.Property<int>("MinimumAge")
                            .HasColumnType("integer");

                        b.Property<decimal>("MinimumProjectCost")
                            .HasColumnType("numeric(12,2)");

                        b.Property<int>("MoratoriumMonths")
                            .HasColumnType("integer");

                        b.Property<string>("Name")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("OfficialUrl")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("RequiredDocuments")
                            .IsRequired()
                            .HasColumnType("jsonb");

                        b.Property<string>("SchemeType")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("SourceDocument")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("Status")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("SupportedDistricts")
                            .IsRequired()
                            .HasColumnType("jsonb");

                        b.Property<string>("TargetGroup")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("VerificationSourceReference")
                            .HasMaxLength(300)
                            .HasColumnType("text");

                        b.Property<DateTime?>("VerifiedOn")
                            .HasColumnType("timestamp with time zone");

                        b.HasKey("Id");

                        b.ToTable("Schemes", (string)null);
                    });

                modelBuilder.Entity("SchemeReady.Api.Models.SchemeRuleRow", b =>
                    {
                        b.Property<string>("SchemeId")
                            .HasMaxLength(64)
                            .HasColumnType("text");

                        b.Property<string>("EligibleBusinessTypes")
                            .IsRequired()
                            .HasColumnType("jsonb");

                        b.Property<string>("EligibleCategories")
                            .IsRequired()
                            .HasColumnType("jsonb");

                        b.Property<string>("GenderRestriction")
                            .IsRequired()
                            .ValueGeneratedOnAdd()
                            .HasColumnType("text")
                            .HasDefaultValue("Any");

                        b.Property<decimal>("IncomeLimit")
                            .HasColumnType("numeric(12,2)");

                        b.Property<decimal>("InterestRate")
                            .HasColumnType("numeric(5,2)");

                        b.Property<int>("MaximumAge")
                            .HasColumnType("integer");

                        b.Property<decimal>("MaximumProjectCost")
                            .HasColumnType("numeric(12,2)");

                        b.Property<int>("MaximumTenureMonths")
                            .HasColumnType("integer");

                        b.Property<int>("MinimumAge")
                            .HasColumnType("integer");

                        b.Property<decimal>("MinimumProjectCost")
                            .HasColumnType("numeric(12,2)");

                        b.Property<int>("MoratoriumMonths")
                            .HasColumnType("integer");

                        b.HasKey("SchemeId");

                        b.ToTable("SchemeRules", (string)null);
                    });

                modelBuilder.Entity("SchemeReady.Api.Models.ScoringWeight", b =>
                    {
                        b.Property<string>("ComponentName")
                            .HasMaxLength(64)
                            .HasColumnType("text");

                        b.Property<int>("Weight")
                            .HasColumnType("integer");

                        b.HasKey("ComponentName");

                        b.ToTable("ScoringWeights", (string)null);
                    });

                modelBuilder.Entity("SchemeReady.Api.Models.StoredDocument", b =>
                    {
                        b.Property<Guid>("Id")
                            .HasColumnType("uuid");

                        b.Property<string>("ApplicationPackId")
                            .HasMaxLength(64)
                            .HasColumnType("text");

                        b.Property<long>("ByteLength")
                            .HasColumnType("bigint");

                        b.Property<string>("ContentType")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<DateTime?>("DeletedAt")
                            .HasColumnType("timestamp with time zone");

                        b.Property<string>("DocumentKey")
                            .IsRequired()
                            .HasMaxLength(32)
                            .HasColumnType("text");

                        b.Property<string>("OriginalFileName")
                            .IsRequired()
                            .HasMaxLength(255)
                            .HasColumnType("text");

                        b.Property<string>("OwnerUserId")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("Sha256")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<string>("StoredFileName")
                            .IsRequired()
                            .HasColumnType("text");

                        b.Property<DateTime>("UploadedAt")
                            .HasColumnType("timestamp with time zone");

                        b.HasKey("Id");

                        b.HasIndex("ApplicationPackId");

                        b.HasIndex("OwnerUserId", "DocumentKey")
                            .IsUnique()
                            .HasDatabaseName("ux_stored_documents_owner_key_live")
                            .HasFilter("\"DeletedAt\" IS NULL");

                        b.ToTable("StoredDocuments", (string)null);
                    });

                modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                    {
                        b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                            .WithMany()
                            .HasForeignKey("RoleId")
                            .OnDelete(DeleteBehavior.Cascade)
                            .IsRequired();
                    });

                modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                    {
                        b.HasOne("SchemeReady.Api.Auth.ApplicationUser", null)
                            .WithMany()
                            .HasForeignKey("UserId")
                            .OnDelete(DeleteBehavior.Cascade)
                            .IsRequired();
                    });

                modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                    {
                        b.HasOne("SchemeReady.Api.Auth.ApplicationUser", null)
                            .WithMany()
                            .HasForeignKey("UserId")
                            .OnDelete(DeleteBehavior.Cascade)
                            .IsRequired();
                    });

                modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                    {
                        b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                            .WithMany()
                            .HasForeignKey("RoleId")
                            .OnDelete(DeleteBehavior.Cascade)
                            .IsRequired();

                        b.HasOne("SchemeReady.Api.Auth.ApplicationUser", null)
                            .WithMany()
                            .HasForeignKey("UserId")
                            .OnDelete(DeleteBehavior.Cascade)
                            .IsRequired();
                    });

                modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                    {
                        b.HasOne("SchemeReady.Api.Auth.ApplicationUser", null)
                            .WithMany()
                            .HasForeignKey("UserId")
                            .OnDelete(DeleteBehavior.Cascade)
                            .IsRequired();
                    });

                modelBuilder.Entity("SchemeReady.Api.Auth.OfficerPartnerAssignment", b =>
                    {
                        b.HasOne("SchemeReady.Api.Models.ChannelPartner", null)
                            .WithMany()
                            .HasForeignKey("PartnerId")
                            .OnDelete(DeleteBehavior.Cascade)
                            .IsRequired();

                        b.HasOne("SchemeReady.Api.Auth.ApplicationUser", null)
                            .WithMany()
                            .HasForeignKey("UserId")
                            .OnDelete(DeleteBehavior.Cascade)
                            .IsRequired();
                    });

                modelBuilder.Entity("SchemeReady.Api.Auth.RefreshToken", b =>
                    {
                        b.HasOne("SchemeReady.Api.Auth.ApplicationUser", null)
                            .WithMany()
                            .HasForeignKey("UserId")
                            .OnDelete(DeleteBehavior.Cascade)
                            .IsRequired();
                    });

                modelBuilder.Entity("SchemeReady.Api.Models.SchemeRuleRow", b =>
                    {
                        b.HasOne("SchemeReady.Api.Models.Scheme", null)
                            .WithMany()
                            .HasForeignKey("SchemeId")
                            .OnDelete(DeleteBehavior.Cascade)
                            .IsRequired();
                    });

                modelBuilder.Entity("SchemeReady.Api.Models.StoredDocument", b =>
                    {
                        b.HasOne("SchemeReady.Api.Data.ApplicationPackRow", null)
                            .WithMany()
                            .HasForeignKey("ApplicationPackId")
                            .OnDelete(DeleteBehavior.SetNull);

                        b.HasOne("SchemeReady.Api.Auth.ApplicationUser", null)
                            .WithMany()
                            .HasForeignKey("OwnerUserId")
                            .OnDelete(DeleteBehavior.Cascade)
                            .IsRequired();
                    });
#pragma warning restore 612, 618
        }
    }
}
